
spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://122.51.246.46:3306/nomadic-soul #url
    username: nomadic-soul  #用户名
    password: feifei12138...  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动


mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.nomadicsoulmgl.nomadicsoul.bean #配置实体类