
spring:
  datasource:
    name: ns
    url: jdbc:mysql://122.51.246.46:3306/nomadic-soul
    username: nomadic-soul
    password: feifei12138...
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nomadicsoulmgl.nomadicsoul.bean

server:
  port: 8089
  servlet:
    context-path: /ns